import { Brand } from "@/types/brand";

const brandsData: Brand[] = [
  {
    id: 1,
    name: "UIdeck",
    href: "https://uideck.com",
    image: "/images/brands/accountlogist.png",
    imageLight: "/images/brands/uideck-light.svg",
  },
  {
    id: 2,
    name: "Lineicons",
    href: "https://lineicons.com",
    image: "/images/brands/belux.png",
    imageLight: "/images/brands/lineicons-light.svg",
  },
  {
    id: 3,
    name: "Ayro UI",
    href: "https://ayroui.com",
    image: "/images/brands/bizadvisor.svg",
    imageLight: "/images/brands/ayroui-light.svg",
  },
  {
    id: 4,
    name: "PlainAdmin",
    href: "https://plainadmin.com",
    image: "/images/brands/cinnalanka2.png",
    imageLight: "/images/brands/plainadmin-light.svg",
  },
  {
    id: 5,
    name: "Cinnaro",
    href: "#",
    image: "/images/brands/cinnaro.png",
    imageLight: "/images/brands/plainadmin-light.svg",
  },
  {
    id: 6,
    name: "Githnara",
    href: "#",
    image: "/images/brands/githnara2.png",
    imageLight: "/images/brands/figma-light.svg",
  },
  {
    id: 7,
    name: "Property",
    href: "#",
    image: "/images/brands/property.png",
    imageLight: "/images/brands/sketch-light.svg",
  },
  {
    id: 8,
    name: "Agra",
    href: "#",
    image: "/images/brands/agra.jpeg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 9,
    name: "Company",
    href: "#",
    image: "/images/brands/company.jpeg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 10,
    name: "Electrical",
    href: "#",
    image: "/images/brands/electrical.jpeg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 11,
    name: "Rase",
    href: "#",
    image: "/images/brands/rase.jpeg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 12,
    name: "Synergy",
    href: "#",
    image: "/images/brands/synergy.jpeg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 13,
    name: "Talent",
    href: "#",
    image: "/images/brands/talent.jpeg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 14,
    name: "Airforce",
    href: "#",
    image: "/images/brands/airforce.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 15,
    name: "CEAT",
    href: "#",
    image: "/images/brands/ceat.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 16,
    name: "Vasan",
    href: "#",
    image: "/images/brands/vasan.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 17,
    name: "Majestic City",
    href: "#",
    image: "/images/brands/mc.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 18,
    name: "Intelliglows",
    href: "#",
    image: "/images/brands/intelliglows.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 19,
    name: "Lead",
    href: "#",
    image: "/images/brands/lead1.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 20,
    name: "Diaper Deal",
    href: "#",
    image: "/images/brands/diaperdeal.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 21,
    name: "Diaper Store",
    href: "#",
    image: "/images/brands/diaperstore.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 22,
    name: "Well Living",
    href: "#",
    image: "/images/brands/well-living.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 23,
    name: "Falcon",
    href: "#",
    image: "/images/brands/falcon.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 24,
    name: "MNM",
    href: "#",
    image: "/images/brands/mnm.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 25,
    name: "Hi Bakers",
    href: "#",
    image: "/images/brands/hibakers.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 26,
    name: "Janatha",
    href: "#",
    image: "/images/brands/janatha.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 27,
    name: "C Needs",
    href: "#",
    image: "/images/brands/cneeds.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 28,
    name: "Prime",
    href: "#",
    image: "/images/brands/prime.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 29,
    name: "Abda",
    href: "#",
    image: "/images/brands/abda.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 30,
    name: "Dilantha",
    href: "#",
    image: "/images/brands/dilantha.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 31,
    name: "Everest",
    href: "#",
    image: "/images/brands/Everest.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 32,
    name: "Evoke",
    href: "#",
    image: "/images/brands/evoke.jpg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 33,
    name: "Global",
    href: "#",
    image: "/images/brands/Global.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 34,
    name: "Sakura",
    href: "#",
    image: "/images/brands/Sakura.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 35,
    name: "LC",
    href: "#",
    image: "/images/brands/Lc.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 36,
    name: "UMS",
    href: "#",
    image: "/images/brands/Ums.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 37,
    name: "Printek",
    href: "#",
    image: "/images/brands/printek.jpg",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 38,
    name: "Sahal",
    href: "#",
    image: "/images/brands/Sahal.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 39,
    name: "Dragon",
    href: "#",
    image: "/images/brands/Dragon.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 40,
    name: "Manath",
    href: "#",
    image: "/images/brands/Manath.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 41,
    name: "Pro Realtors",
    href: "#",
    image: "/images/brands/Prorealtors.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 42,
    name: "TC",
    href: "#",
    image: "/images/brands/Tc.png",
    imageLight: "/images/brands/github-light.svg",
  },
  {
    id: 43,
    name: "Agra",
    href: "#",
    image: "/images/brands/Agra.png",
    imageLight: "/images/brands/github-light.svg",
  },
];

export default brandsData;